rework hce option
bench: 5888903

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -11,6 +11,11 @@ if ! zig build check; then
     exit 1
 fi
 
+if ! zig build -Deval=hce check; then
+    echo "hce build failed"
+    exit 1
+fi
+
 if ! zig build --release=small test -- tests/standard.epd; then
     echo "tests failed"
     exit 1
